### PR TITLE
feat: add fingers bone map

### PR DESCRIPTION
**Pull request by jlsneto**
Add fingers and use in ik retargeting prototype

Animação2

### CODE REVIEW

**Comment by sketchpunk** [comment]
whoa, im impressed. Nice to see fingers working but im sorry to say that I cannot accept this pull request. I avoided the hands because I wanted to try a different approach then using the SwingTwist solver which is more for the spine of the character.

The fingers have a limited range of movement & it bends fairly evenly. Fingers are more like limbs with hinge joints where a spine functions more like ball joints. For data I was thinking of a single vector to handle the swing rotation then a scalar value between 0 & 1 to denote how extended the finger is. Because there are 10 total fingers, there is much to process if doing it with IK when there really isn't a need for it. Since there is no need to IK target fingers & the data I had in mind is simpler it makes me think its something that should be worked on in local space for each chain to avoid all the math related to local > world > local conversion which is more optimized way to handle things, but I may need to precompute each local space's X rotation axis since the bone's local twist rotation can be guaranteed to not always be the same nor world space aligned, limbs alone has proven that to me over the years :)

If this is an area you're interested in contributing, we can discuss further either in text or video chat. Its been awhile, but I believe I did things like this a long while ago when prototyped hand tracking with meta quest. I believe I used some of those ideas to build it. You can check out the project at this repo - https://sketchpunklabs.github.io/xrhand/

**Comment by jlsneto** [comment]
> whoa, im impressed. Nice to see fingers working but im sorry to say that I cannot accept this pull request. I avoided the hands because I wanted to try a different approach then using the SwingTwist solver which is more for the spine of the character.
> 
> The fingers have a limited range of movement & it bends fairly evenly. Fingers are more like limbs with hinge joints where a spine functions more like ball joints. For data I was thinking of a single vector to handle the swing rotation then a scalar value between 0 & 1 to denote how extended the finger is. Because there are 10 total fingers, there is much to process if doing it with IK when there really isn't a need for it. Since there is no need to IK target fingers & the data I had in mind is simpler it makes me think its something that should be worked on in local space for each chain to avoid all the math related to local > world > local conversion which is more optimized way to handle things, but I may need to precompute each local space's X rotation axis since the bone's local twist rotation can be guaranteed to not always be the same nor world space aligned, limbs alone has proven that to me over the years :)
> 
> If this is an area you're interested in contributing, we can discuss further either in text or video chat. Its been awhile, but I believe I did things like this a long while ago when prototyped hand tracking with meta quest. I believe I used some of those ideas to build it. You can check out the project at this repo - https://sketchpunklabs.github.io/xrhand/

Thank you for reviewing my pull request. I understand your decision and appreciate the detailed feedback.

Your approach using a single vector for swing rotation and a scalar for finger extension sounds efficient. I agree that working in local space for each chain is a more optimized method.

I’m interested in contributing further and would love to discuss this more. I’ll also check out the project at the provided repo link.

**Comment by sketchpunk** [comment]
No problem. I feel bad for all the work you did to get it working, so you deserved more than "sorry, I can't use this". Thank you for your efforts either way, hopefully you learn something new at least from what you did.

**Comment by jlsneto** [comment]
> No problem. I feel bad for all the work you did to get it working, so you deserved more than "sorry, I can't use this". Thank you for your efforts either way, hopefully you learn something new at least from what you did.

I was happy with your answer and has already given me some insights, I really want to contribute to the project. I'll talk to you there on "X".

**Comment by sketchpunk** [comment]
Here are some hand rig UIs i find interesting to explore. Gives an ideas of the direction Im going with the simpler way to handle hands. These two UI concepts makes it look super easy to pose all the fingers of a hand with little input from the user :)

https://x.com/amareshbeuria/status/1795111969579569332

https://x.com/function_chiba/status/1615184662602874882

**Pull request closed without merging**
